spring:
  config:
    import: optional:/app/config/springboot-webservice/application-realdb.yml , optional:C:\Users\carol\Desktop\HC\front\server\perfume_webservice\src\main\resources\application-realdb.yml
  profiles:
    group :
      local : local,comm
      set1 : set1,comm
      set2 : set2,comm
    active: local

